### ISSUE TITLE
How big is the final packaged code?

### ISSUE THREAD

**Issue by yellow1912** [erql/rx-rql#1]
Would be nice to specify this somewhere so we know the performance impact if any to use it in the browser environment.

Thank you for the library.

**Comment by kosich** [comment]
Hi, @yellow1912 ! I'm glad that you found this lib interesting! 🙂

Good point, I'll add this to README!

The package itself is quite small and relies only on standard Rx' API: `Observable` and `Subject`. If you use Rx, you already use those. So you only add a few kB of this package.

The size depends on how you import/bundle and how many operators you use, but generally it's around 1~3 kB, here's a [Bundlephobia report](https://bundlephobia.com/result?p=rx-rql)
